spring.application.name=artisanal-backend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://souhaila_db:souhaila123@cluster0.pssnhan.mongodb.net/artisanal_db?retryWrites=true&w=majority

spring.data.mongodb.database=artisanal_db
spring.data.mongodb.auto-index-creation=true

spring.ai.vectorstore.type=none